apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBindings
metadata:
  name: full-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: bob
  apiGroup: rbac.authorization.k8s.io
