apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-tcp-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns-svc-lb
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
    - name: tcp-dns
      protocol: TCP
      port: 53
      targetPort: 53
