apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-view-role-binding
  namespace: dev
roleRef:
  apiGroup: ""
  kind: Role
  name: view
subjects:
- kind: ServiceAccount
  name: ken
