apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-role-binding
  namespase: prometheus
roleRef:
  kind: Role
  name: prometheus-role
subjects:
- kind: ServiceAccount
  name: carol
