apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: no-full-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:basic-user
subjects:
- kind: ServiceAccount
  name: dave

